### ISSUE TITLE
Translation strings showing

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud-frontend#818] opened 2024-11-07 20:32 UTC
Clicking refresh on the upload page sometimes shows the translation keys instead of the proper translated strings:

![image](https://github.com/user-attachments/assets/3e94f257-26c4-47f0-a7eb-bdc87a286a72)

**Comment by mitchelljkotler** [comment] 2024-11-07 21:21
Also happening for me on add-on search:
![image](https://github.com/user-attachments/assets/f2e0762d-c2ec-4702-9aeb-96bc270d31a2)

**Comment by eyeseast** [comment] 2024-11-08 16:34
I can't reproduce this on uploads or the add-on list.

**Comment by eyeseast** [comment] 2024-11-21 21:51
Closing this based on #868 but please reopen if you see this again.

**Closed by eyeseast** 2024-11-21 21:51 UTC
Labels: bug, i18n
